version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: skillora
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5435:5435'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
