services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: skillora
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5435:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d skillora']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./backend/.env
    ports:
      - '8080:8000'
      - '5678:5678'
    environment:
      - PYTHONPATH=/app
    command: >
      python -m debugpy --listen 0.0.0.0:5678
      -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  pgdata:
