version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: skillora
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5435:5432'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  backend:
    build: .
    ports:
      - '8080:8000'
      - '5678:5678'
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
