name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker-compose.yml'
      - 'Makefile'
      - '.github/workflows/ci.yml'
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker-compose.yml'
      - 'Makefile'
      - '.github/workflows/ci.yml'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend • lint + tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            backend/requirements*.txt

      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff (lint)
        working-directory: backend
        run: ruff check . --no-cache

      - name: Black (check only)
        working-directory: backend
        run: black --check .

      - name: Pytest (list collected)
        working-directory: backend
        run: pytest --collect-only -q

      - name: Pytest (run)
        working-directory: backend
        # plugin de warnings já está desativado no pytest.ini (-p no:warnings)
        run: pytest -vv -ra

  frontend:
    name: Frontend • lint + typecheck + tests + build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: ESLint
        working-directory: frontend
        run: npm run lint

      - name: Typecheck (tsc)
        working-directory: frontend
        run: npm run typecheck

      - name: Vitest
        working-directory: frontend
        run: npm run test -- --run

      - name: Build (Vite)
        working-directory: frontend
        run: npm run build
